#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(FOCUS_PUNCH) \
    F(DRAGON_CLAW) \
    F(WATER_PULSE) \
    F(CALM_MIND) \
    F(ROAR) \
    F(TOXIC) \
    F(HAIL) \
    F(BULK_UP) \
    F(BULLET_SEED) \
    F(HIDDEN_POWER) \
    F(SUNNY_DAY) \
    F(TAUNT) \
    F(ICE_BEAM) \
    F(BLIZZARD) \
    F(HYPER_BEAM) \
    F(LIGHT_SCREEN) \
    F(PROTECT) \
    F(RAIN_DANCE) \
    F(GIGA_DRAIN) \
    F(SAFEGUARD) \
    F(FRUSTRATION) \
    F(SOLAR_BEAM) \
    F(IRON_TAIL) \
    F(THUNDERBOLT) \
    F(THUNDER) \
    F(EARTHQUAKE) \
    F(RETURN) \
    F(DIG) \
    F(PSYCHIC) \
    F(SHADOW_BALL) \
    F(BRICK_BREAK) \
    F(DOUBLE_TEAM) \
    F(REFLECT) \
    F(SHOCK_WAVE) \
    F(FLAMETHROWER) \
    F(SLUDGE_BOMB) \
    F(SANDSTORM) \
    F(FIRE_BLAST) \
    F(ROCK_TOMB) \
    F(AERIAL_ACE) \
    F(TORMENT) \
    F(FACADE) \
    F(SECRET_POWER) \
    F(REST) \
    F(ATTRACT) \
    F(THIEF) \
    F(STEEL_WING) \
    F(SKILL_SWAP) \
    F(SNATCH) \
    F(OVERHEAT) \
    F(U_TURN) \
    F(X_SCISSOR) \
    F(BUG_BUZZ) \
    F(POLLEN_PUFF) \
    F(DARK_PULSE) \
    F(NASTY_PLOT) \
    F(DRAGON_PULSE) \
    F(DRAGON_DANCE) \
    F(THUNDER_PUNCH) \
    F(WILD_CHARGE) \
    F(ELECTRIC_TERRAIN) \
    F(THUNDER_WAVE) \
    F(PLAY_ROUGH) \
    F(DAZZLING_GLEAM) \
    F(DRAINING_KISS) \
    F(MISTY_TERRAIN) \
    F(CLOSE_COMBAT) \
    F(AURA_SPHERE) \
    F(FOCUS_BLAST) \
    F(FIRE_PUNCH) \
    F(FLARE_BLITZ) \
    F(WILL_O_WISP) \
    F(BRAVE_BIRD) \
    F(AIR_SLASH) \
    F(HURRICANE) \
    F(TAILWIND) \
    F(SHADOW_CLAW) \
    F(HEX) \
    F(GRASSY_GLIDE) \
    F(SOLAR_BLADE) \
    F(TRAILBLAZE) \
    F(GRASSY_TERRAIN) \
    F(EARTH_POWER) \
    F(SPIKES) \
    F(ICE_PUNCH) \
    F(ICE_SPINNER) \
    F(POISON_JAB) \
    F(GUNK_SHOT) \
    F(TOXIC_SPIKES) \
    F(ZEN_HEADBUTT) \
    F(TRICK_ROOM) \
    F(PSYCHIC_TERRAIN) \
    F(TRICK) \
    F(STONE_EDGE) \
    F(POWER_GEM) \
    F(STEALTH_ROCK) \
    F(IRON_HEAD) \
    F(FLASH_CANNON) \
    F(FLIP_TURN) \
    F(SCALD) 

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
